version: '3'

services:
  neo_dest:
    image: neo4j:4.2.0
    user: ${UID:-1000}:${GID:-1000}
    volumes:
      - ../neo4j_playground_storage:/data
    environment:
      NEO4J_AUTH: "neo4j/test"

  app:
    image: node:16-slim
    command: sh -c "cd /app && yarn install && yarn start"
    #build: ./docker-node/
    volumes:
      - ./:/app
    ports:
      - 3000:3000
